<?php

namespace App\DataFixtures;

use App\Entity\SectorOfOffer;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class SectorOfOfferFixture extends Fixture
{


    /**
     * @param ObjectManager $manager
     * @return void
     */
    public function load(ObjectManager $manager)
    {
        $sectorOfOffers = [
            SectorOfOffer::CULTURE_ET_PRODUCTION_ANIMALE_CHASSE_ET_SERVICES_ANNEXES,
            SectorOfOffer::SYLVICULTURE_ET_EXPLOITATION_FORESTIERE,
            SectorOfOffer::PECHE_ET_AQUACULTURE,
            SectorOfOffer::EXTRACTION_DE_HOUILLE_ET_DE_LIGNITE,
            SectorOfOffer::EXTRACTION_D_HYDROCARBURES,
            SectorOfOffer::EXTRACTION_DE_MINERAIS_METALLIQUES,
            SectorOfOffer::AUTRES_INDUSTRIES_EXTRACTIVES,
            SectorOfOffer::SERVICES_DE_SOUTIEN_AUX_INDUSTRIES_EXTRACTIVES,
            SectorOfOffer::INDUSTRIES_ALIMENTAIRES,
            SectorOfOffer::FABRICATION_DE_BOISSONS,
            SectorOfOffer::FABRICATION_DE_PRODUITS_A_BASE_DE_TABAC,
            SectorOfOffer::FABRICATION_DE_TEXTILES,
            SectorOfOffer::INDUSTRIE_DE_L_HABILLEMENT,
            SectorOfOffer::INDUSTRIE_DU_CUIR_ET_DE_LA_CHAUSSURE,
            SectorOfOffer::TRAVAIL_DU_BOIS_ET_FABRICATION_D_ARTICLES_EN_BOIS_ET_EN_LIEGE,
            SectorOfOffer::INDUSTRIE_DU_PAPIER_ET_DU_CARTON,
            SectorOfOffer::IMPRIMERIE_ET_REPRODUCTION_D_ENREGISTREMENTS,
            SectorOfOffer::COKEFACTION_ET_RAFFINAGE,
            SectorOfOffer::INDUSTRIE_CHIMIQUE,
            SectorOfOffer::INDUSTRIE_PHARMACEUTIQUE,
            SectorOfOffer::FABRICATION_DE_PRODUITS_EN_CAOUTCHOUC_ET_EN_PLASTIQUE,
            SectorOfOffer::FABRICATION_D_AUTRES_PRODUITS_MINERAUX_NON_METALLIQUES,
            SectorOfOffer::METALLURGIE,
            SectorOfOffer::FABRICATION_DE_PRODUITS_METALLIQUES_A_L_EXCEPTION_DES_MACHINES_ET_DES_EQUIPEMENTS,
            SectorOfOffer::FABRICATION_DE_PRODUITS_INFORMATIQUES_ELECTRONIQUES_ET_OPTIQUES,
            SectorOfOffer::FABRICATION_D_EQUIPEMENTS_ELECTRIQUES,
            SectorOfOffer::FABRICATION_DE_MACHINES_ET_EQUIPEMENTS_N_C_A,
            SectorOfOffer::INDUSTRIE_AUTOMOBILE,
            SectorOfOffer::FABRICATION_D_AUTRES_MATERIELS_DE_TRANSPORT,
            SectorOfOffer::FABRICATION_DE_MEUBLES,
            SectorOfOffer::AUTRES_INDUSTRIES_MANUFACTURIERES,
            SectorOfOffer::REPARATION_ET_INSTALLATION_DE_MACHINES_ET_D_EQUIPEMENTS,
            SectorOfOffer::PRODUCTION_ET_DISTRIBUTION_D_ELECTRICITE_DE_GAZ_DE_VAPEUR_ET_D_AIR_CONDITIONNE,
            SectorOfOffer::CAPTAGE_TRAITEMENT_ET_DISTRIBUTION_D_EAU,
            SectorOfOffer::COLLECTE_ET_TRAITEMENT_DES_EAUX_USEES,
            SectorOfOffer::COLLECTE_TRAITEMENT_ET_ELIMINATION_DES_DECHETS_RECUPERATION,
            SectorOfOffer::DEPOLLUTION_ET_AUTRES_SERVICES_DE_GESTION_DES_DECHETS,
            SectorOfOffer::CONSTRUCTION_DE_BATIMENTS,
            SectorOfOffer::GENIE_CIVIL,
            SectorOfOffer::TRAVAUX_DE_CONSTRUCTION_SPECIALISES,
            SectorOfOffer::COMMERCE_ET_REPARATION_D_AUTOMOBILES_ET_DE_MOTOCYCLES,
            SectorOfOffer::COMMERCE_DE_GROS_A_L_EXCEPTION_DES_AUTOMOBILES_ET_DES_MOTOCYCLES,
            SectorOfOffer::COMMERCE_DE_DETAIL_A_L_EXCEPTION_DES_AUTOMOBILES_ET_DES_MOTOCYCLES,
            SectorOfOffer::TRANSPORTS_TERRESTRES_ET_TRANSPORT_PAR_CONDUITES,
            SectorOfOffer::TRANSPORTS_PAR_EAU,
            SectorOfOffer::TRANSPORTS_AERIENS,
            SectorOfOffer::ENTREPOSAGE_ET_SERVICES_AUXILIAIRES_DES_TRANSPORTS,
            SectorOfOffer::ACTIVITES_DE_POSTE_ET_DE_COURRIER,
            SectorOfOffer::HEBERGEMENT,
            SectorOfOffer::RESTAURATION,
            SectorOfOffer::EDITION,
            SectorOfOffer::PRODUCTION_DE_FILMS_CINEMATOGRAPHIQUES_DE_VIDEO_ET_DE_PROGRAMMES_DE_TELEVISION_ENREGISTREMENT_SONORE_ET_EDITION_MUSICALE,
            SectorOfOffer::PROGRAMMATION_ET_DIFFUSION,
            SectorOfOffer::TELECOMMUNICATIONS,
            SectorOfOffer::PROGRAMMATION_CONSEIL_ET_AUTRES_ACTIVITES_INFORMATIQUES,
            SectorOfOffer::SERVICES_D_INFORMATION,
            SectorOfOffer::ACTIVITES_DES_SERVICES_FINANCIERS_HORS_ASSURANCE_ET_CAISSES_DE_RETRAITE,
            SectorOfOffer::ASSURANCE,
            SectorOfOffer::ACTIVITES_AUXILIAIRES_DE_SERVICES_FINANCIERS_ET_D_ASSURANCE,
            SectorOfOffer::ACTIVITES_IMMOBILIERES,
            SectorOfOffer::ACTIVITES_JURIDIQUES_ET_COMPTABLES,
            SectorOfOffer::ACTIVITES_DES_SIEGES_SOCIAUX_CONSEIL_DE_GESTION,
            SectorOfOffer::ACTIVITES_D_ARCHITECTURE_ET_D_INGENIERIE_ACTIVITES_DE_CONTROLE_ET_ANALYSES_TECHNIQUES,
            SectorOfOffer::RECHERCHE_DEVELOPPEMENT_SCIENTIFIQUE,
            SectorOfOffer::PUBLICITE_ET_ETUDES_DE_MARCHE,
            SectorOfOffer::AUTRES_ACTIVITES_SPECIALISEES_SCIENTIFIQUES_ET_TECHNIQUES,
            SectorOfOffer::ACTIVITES_VETERINAIRES,
            SectorOfOffer::ACTIVITES_DE_LOCATION_ET_LOCATION_BAIL,
            SectorOfOffer::ACTIVITES_LIEES_A_L_EMPLOI,
            SectorOfOffer::ACTIVITES_DES_AGENCES_DE_VOYAGE_VOYAGISTES_SERVICES_DE_RESERVATION_ET_ACTIVITES_CONNEXES,
            SectorOfOffer::ENQUETES_ET_SECURITE,
            SectorOfOffer::SERVICES_RELATIFS_AUX_BATIMENTS_ET_AMENAGEMENT_PAYSAGER,
            SectorOfOffer::ACTIVITES_ADMINISTRATIVES_ET_AUTRES_ACTIVITES_DE_SOUTIEN_AUX_ENTREPRISES,
            SectorOfOffer::ADMINISTRATION_PUBLIQUE_ET_DEFENSE_SECURITE_SOCIALE_OBLIGATOIRE,
            SectorOfOffer::ENSEIGNEMENT,
            SectorOfOffer::ACTIVITES_POUR_LA_SANTE_HUMAINE,
            SectorOfOffer::HEBERGEMENT_MEDICO_SOCIAL_ET_SOCIAL,
            SectorOfOffer::ACTION_SOCIALE_SANS_HEBERGEMENT,
            SectorOfOffer::ACTIVITES_CREATIVES_ARTISTIQUES_ET_DE_SPECTACLE,
            SectorOfOffer::BIBLIOTHEQUES_ARCHIVES_MUSEES_ET_AUTRES_ACTIVITES_CULTURELLES,
            SectorOfOffer::ORGANISATION_DE_JEUX_DE_HASARD_ET_D_ARGENT,
            SectorOfOffer::ACTIVITES_SPORTIVES_RECREATIVES_ET_DE_LOISIRS,
            SectorOfOffer::ACTIVITES_DES_ORGANISATIONS_ASSOCIATIVES,
            SectorOfOffer::REPARATION_D_ORDINATEURS_ET_DE_BIENS_PERSONNELS_ET_DOMESTIQUES,
            SectorOfOffer::AUTRES_SERVICES_PERSONNELS,
            SectorOfOffer::ACTIVITES_DES_MENAGES_EN_TANT_QU_EMPLOYEURS_DE_PERSONNEL_DOMESTIQUE,
            SectorOfOffer::ACTIVITES_INDIFFERENCIEES_DES_MENAGES_EN_TANT_QUE_PRODUCTEURS_DE_BIENS_ET_SERVICES_POUR_USAGE_PROPRE,
            SectorOfOffer::ACTIVITES_DES_ORGANISATIONS_ET_ORGANISMES_EXTRATERRITORIAUX,
        ];

        foreach ($sectorOfOffers as $sectorOfOffer) {

            $sectorOfOfferObj = new SectorOfOffer();
            $sectorOfOfferObj->setLabel($sectorOfOffer);
            $manager->persist($sectorOfOfferObj);
        }


        $manager->flush();
    }
}